config/routes.rb
Rails.application.routes.draw do

  get 'gallery/index'
  get 'gallery', to:'gallery#index'

  get 'games/index'
  get 'games', to:'games#index'

  get 'hackathon_a/index'
  get 'hackathon_a', to:'hackathon_a#index'

  get 'hackathon_b/index'
  get 'hackathon_b', to:'hackathon_b#index'

  get 'clover/index'
  get 'clover', to:'clover#index'

  mount Ckeditor::Engine => '/ckeditor'
  get 'yozawiza/top'
  get 'yozawiza', to:'yozawiza#top'

  get 'yozawiza/about'

  get 'yozawiza/system'

  get 'yozawiza/spec'

  get 'yozawiza/movie'

  get 'top/about'

  get 'top/system'

  get 'top/spec'

  get 'top/movie'

  root :to => 'home#index'

  get 'hackathon2/index'
  get 'hackathon2', to:'hackathon2#index'

  get 'hackathon/index'
  get 'hackathon', to:'hackathon#index'

  resources :events

  resources :topics

  resources :categories

  resources :admin
  resources :contacts, except: [:show, :edit, :update ,:destroy]

  get 'products/index'
  get 'products', to:'products#index'
  get 'products/about'
  get 'products/system'
  get 'products/character'
  get 'products/download'

  get 'festivals/index'
  get 'festivals', to:'festivals#index'
  get "/festival/" => redirect("/festivals/index")
  get "/festival/index" => redirect("/festivals/index")

  resources :images, except: [:show, :edit, :update]

  get 'home/index'
  get 'home', to:'home#index'
  get 'home/activity'
  get 'home/news'
  get 'home/event'

  devise_for :accounts

  devise_scope :account do
    get '/accounts/sign_out' => 'devise/sessions#destroy'
  end

  as :account do
    get 'accounts/edit' => 'devise/registrations#edit', :as => 'edit_account_registration'
    put 'accounts' => 'devise/registrations#update', :as => 'account_registration'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :info
    belongs_to :image

    validates :name,
        presence: {message:'を入力してください。'},
        uniqueness: {message:'同じものが存在しています。'},
        length: {maximum: 15}
    
    validates :image_id,
        presence: {message:'を入力してください。'}

end

app/models/contact.rb
class Contact < ApplicationRecord
    validates :name,
        presence: {message:'を入力してください。'}
    validates :mail,
        presence: {message:'を入力してください。'}
    validates :main, presence: true, format: { with: /\p{Hiragana}/, \
        message: '(お問い合わせ内容)には日本語を含めてください。(Text must contain hiragana.)' }
end

app/models/event.rb
class Event < ApplicationRecord
    validates :event_name,
        presence: {message:'を入力してください。'}
    validates :event_date,
        presence: {message:'を入力してください。'}
end

app/models/image.rb
class Image < ApplicationRecord

  mount_uploader :tag, ImageUploader

  has_many :category
  has_many :topic

  validates :tag, presence: {message:'を入力してください。'}

end

app/models/info.rb
class Info < ApplicationRecord
    belongs_to :category

    validates :main,
        presence: {message:'を入力してください。'}
    validates :my_date,
        presence: {message:'を入力してください。'}
    validates :category_id,
        presence: {message:'を入力してください。'}
end

app/models/topic.rb
class Topic < ApplicationRecord
    belongs_to :image

    validates :image_id,
        presence: {message:'を入力してください。'}
    validates :memo,
        presence: {message:'を入力してください。'}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_account!
  
  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.create category_params
    if @category.save then
      redirect_to '/categories'
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find params[:id]
  end

  def update
    @category = Category.find params[:id]
    @category.update category_params
    if @category.save then
      redirect_to '/categories'
    else
      render'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to'/categories'
  end

  private
  def category_params
    params.require(:category).permit(:name, :image_id)
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clover_helper.rb
module CloverHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/festivals_helper.rb
module FestivalsHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/hackathon2_helper.rb
module Hackathon2Helper
end

app/helpers/hackathon_helper.rb
module HackathonHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/yozawiza_helper.rb
module YozawizaHelper
end

app/views/categories/_form.html.erb
<% if category.errors.any? %>
<ul>
    <% category.errors.full_messages.each do |err| %>
        <li><%= err %></li>
    <% end %>
</ul>
<% end %>

<%= form_for category do |form| %>
<table>
    <tr><th>カテゴリ名</th>
        <td><%= form.text_field :name %></td></tr>
    <tr><th>画像ID</th>
        <td><%= form.text_field :image_id %></td></tr>
    <tr><th></th>
        <td><%= form.submit "送信" %></td></tr>
</table>
<% end %>

app/views/categories/edit.html.erb
<div class="body">
<h1>カテゴリ設定</h1>
<p>カテゴリの編集</p>
<%= render 'form', category:@category %>
<p><a href="/categories">戻る</a></p>
</div>

app/views/categories/index.html.erb
<div class="body">
<h1>カテゴリ設定</h1>

<p><a href="/categories/new">新カテゴリの追加</a></p>

<table>
    <tr>
        <th>カテゴリ</th><th>画像ID</th><th>画像</th><th>編集</th><th>削除</th>
    </tr>
    <% @categories.each do |obj| %>
    <tr>
        <td><%= obj.name %></td>
        <td><%= obj.image_id %></td>
        <td><%= image_tag obj.image.tag, :width => '130' %></td>
        <td><a href="/categories/<%= obj.id %>/edit">編集</a></td>
        <td><%= link_to '削除', obj, method: :delete, data: { confirm: 'このデータを削除しますか?' } %></td>
    </tr>
    <% end %>
</table>

<p><a href="/admin">管理者トップへ</a></p>
<p><a href="/images">画像設定へ</a></p>
<%=link_to 'サインアウト', destroy_account_session_path, method: :delete %>
</div>

app/views/categories/new.html.erb
<div class="body">
<h1>カテゴリ設定</h1>
<p>新規作成</p>
<%= render 'form', category:@category %>
<p><a href="/categories">戻る</a></p>
</div>